Add accessibility.md
techmmunity/articles-stock pull request #1
Opened 2021-05-25 11:16 UTC by alessandrohenriqueramos

2021-05-26 00:12 UTC, henriqueleite42 requested changes

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Um navegador consegue transformar a árvore do DOM em uma árvore de acessibilidade, pois muito do DOM tem significado semântico _implícitos_. Assim, a acessibilidade para elementos de HTML nativos, co
`pois muito do DOM tem significado semântico _implícitos_` -> `pois muitos dos elementos do DOM tem significados semânticos _implícitos_`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Um navegador consegue transformar a árvore do DOM em uma árvore de acessibilidade, pois muito do DOM tem significado semântico _implícitos_. Assim, a acessibilidade para elementos de HTML nativos, co
`Assim, a` -> `Com isso, a`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Um navegador consegue transformar a árvore do DOM em uma árvore de acessibilidade, pois muito do DOM tem significado semântico _implícitos_. Assim, a acessibilidade para elementos de HTML nativos, co
`automaticamente. Podemos` -> `automaticamente, e podemos`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Todas as imagens devem ter um atributo `alt`, mas no entanto, nem todos eles precisam conter texto. Imagens importantes devem ter texto alternativo descritivo que descreva sucintamente o que a imagem
`devem ter texto alternativo` -> `devem ter um texto alternativo`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Todas as imagens devem ter um atributo `alt`, mas no entanto, nem todos eles precisam conter texto. Imagens importantes devem ter texto alternativo descritivo que descreva sucintamente o que a imagem
`sucintamente o que a imagem é` -> `com detalhes o conteudo da imagem`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +A [especificação dos Aplicativos Ricos Acessíveis de Internet da Iniciativa para Acessibilidade da Web](https://www.w3.org/TR/wai-aria/) (WAI-ARIA, ou apenas ARIA) é boa para áreas de transição com p
`especificação` -> `Especificação`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +Referência: [https://developers.google.com/web/fundamentals/accessibility?hl=pt-br](https://developers.google.com/web/fundamentals/accessibility?hl=pt-br)
Adicionar sobre Roles

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +`aria-labelledby` nos permite especificar o ID de outro elemento no DOM como o rótulo de um elemento. Isso é muito parecido com usar um elemento `label`, mas, com algumas diferenças.
Especificar as diferenças

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +A especificação ARIA lista oito atributos de relação. Seis deles, `aria-activedescendant`, `aria-controls`, `aria-describedby`, `aria-labelledby`, e `aria-owns`, fazem referência a um ou mais element
Adicionar uma explicação sobre cada `aria-`

2021-05-26 00:12 UTC, henriqueleite42 commented on accessibility.md
> +O tamanho mínimo recomendado do alvo de toque é de cerca de 48 pixels com espaçamento de 8 pixels, para que o dedo do usuário, ao pressionar um alvo, não toque inadvertidamente em outro alvo.
`inadvertidamente` -> `acidentalmente`

2021-05-27 23:42 UTC, alessandrohenriqueramos commented on accessibility.md
> +A [especificação dos Aplicativos Ricos Acessíveis de Internet da Iniciativa para Acessibilidade da Web](https://www.w3.org/TR/wai-aria/) (WAI-ARIA, ou apenas ARIA) é boa para áreas de transição com p
Especificações não deveria ser em maiúsculo, pois ele não faz parte do Aplicativos Ricos Acessíveis de Internet da Iniciativa para Acessibilidade da Web (ARIA).

2021-05-28 00:49 UTC, alessandrohenriqueramos commented on accessibility.md
> +
Adicionado

2021-05-28 00:49 UTC, alessandrohenriqueramos commented on accessibility.md
> +Referência: [https://developers.google.com/web/fundamentals/accessibility?hl=pt-br](https://developers.google.com/web/fundamentals/accessibility?hl=pt-br)
Adicionado

2021-05-28 00:49 UTC, alessandrohenriqueramos commented on accessibility.md
> +A especificação ARIA lista oito atributos de relação. Seis deles, `aria-activedescendant`, `aria-controls`, `aria-describedby`, `aria-labelledby`, e `aria-owns`, fazem referência a um ou mais element
Adicionado

2021-05-28 21:56 UTC, henriqueleite42 requested changes

2021-05-28 21:56 UTC, henriqueleite42 commented on accessibility.md
> +ARIA fornece vários mecanismos para adicionar rótulos e descrições a elementos. Na verdade, ARIA é a única maneira de adicionar texto acessível de ajuda ou descrição. Vejamos as propriedades que a AR
`Na verdade, ARIA é a única maneira de adicionar texto acessível de ajuda ou descrição. ` -> Remover

2021-05-28 21:56 UTC, henriqueleite42 commented on accessibility.md
> +- Você pode usar `aria-labelledby` para se referir a elementos que estão ocultos e que de outra forma, não estariam na árvore de acessibilidade. Por exemplo, você pode adicionar um `span `oculto ao l
Corrigir espaçamento do `span`

2021-05-28 21:56 UTC, henriqueleite42 commented on accessibility.md
> +`aria-activedescendant` desempenha um papel relacionado. Assim como o elemento ativo de uma página é aquele que tem o foco, definir o descendente ativo de um elemento nos permite informar à tecnologi
`aria-activedescendant` desempenha um papel relacionado. -> Remover

2021-05-28 21:56 UTC, henriqueleite42 commented on accessibility.md
> +`aria-activedescendant` desempenha um papel relacionado. Assim como o elemento ativo de uma página é aquele que tem o foco, definir o descendente ativo de um elemento nos permite informar à tecnologi
Alterar esse parafro todo:
`aria-activedescendant` desempenha um papel relacionado. Assim como o elemento ativo de uma página é aquele que tem o foco, definir o descendente ativo de um elemento nos permite informar à tecnologia assistiva que um elemento deve ser apresentado ao usuário como o elemento em foco quando o seu pai, na verdade, tem o foco.

Por:

`aria-activedescendant` nos permite informar à tecnologia assistiva que quando o usuário tentar focar um determinado elemento, ele deve na verdade focar um elemento filho desse determinado elemento. Entenda melhor com o exemplo da imagem abaixo:

2021-05-28 21:56 UTC, henriqueleite42 commented on accessibility.md
> +O item atualmente em foco frequentemente é indicado por um anel de foco, cujo estilo depende tanto do navegador e de qualquer estilo que o autor da página tenha aplicado.
`anel de foco` -> `anel de foco (ou outline)`

2021-05-30 11:40 UTC, henriqueleite42 approved these changes

2021-05-30 11:40 UTC, merged